#include "disassembler.h"

void _unimpl(unsigned char opcode) {
    printf("OPCODE NOT IMPLEMENTED: 0x%02x\n", opcode);
}

int disassemble(unsigned char * rom, uint16_t size) {
    uint16_t counter      = 0;
    uint16_t instructions = 0;
    unsigned char * tmp   = NULL;
    while(counter < size) {
        // skip unneeded cpu operations for space invaders
        tmp = &rom[counter];
        switch(*tmp) {
            case 0x00: printf("NOP\n"); break;
            case 0x01: printf("LXI  B 0x%02x,0x%02x\n", tmp[2], tmp[1]); counter += 2; break;
            case 0x02: printf("STAX B\n"); break;
            case 0x03: printf("INX  B\n"); break;
            case 0x04: printf("INR  B\n"); break;
            case 0x05: printf("DCR  B\n"); break;
            case 0x06: printf("MVI  B 0x%02x\n", tmp[1]); counter += 1; break;
            case 0x07: printf("RLC\n"); break;
            case 0x08: printf("NOP\n"); break;
            case 0x09: printf("DAD  B\n"); break;
            case 0x0a: _unimpl(*tmp); return instructions;
            case 0x0b: _unimpl(*tmp); return instructions;
            case 0x0c: printf("INR  C\n"); break;
            case 0x0d: printf("DCR  C\n"); break;
            case 0x0e: printf("MVI  C 0x%02x\n", tmp[1]); counter += 1; break;
            case 0x0f: printf("RRC\n"); break;
            case 0x10: _unimpl(*tmp); return instructions;
            case 0x11: printf("LXI  D 0x%02x,0x%02x\n", tmp[2], tmp[1]); counter += 2; break;
            case 0x12: printf("STAX D\n"); break;
            case 0x13: printf("INX  D\n"); break;
            case 0x14: printf("INR  D\n"); break;
            case 0x15: printf("DCR  D\n"); break;
            case 0x16: printf("MVI  D 0x%02x\n", tmp[1]); counter += 1; break;
            case 0x17: _unimpl(*tmp); return instructions;
            case 0x18: _unimpl(*tmp); return instructions;
            case 0x19: printf("DAD  D\n"); break;
            case 0x1a: printf("LDAX D\n"); break;
            case 0x1b: printf("DCX  D\n"); break;
            case 0x1c: _unimpl(*tmp); return instructions;
            case 0x1d: _unimpl(*tmp); return instructions;
            case 0x1e: _unimpl(*tmp); return instructions;
            case 0x1f: _unimpl(*tmp); return instructions;
            case 0x20: _unimpl(*tmp); return instructions;
            case 0x21: printf("LXI  H 0x%02x,0x%02x\n", tmp[2], tmp[1]); counter += 2; break;
            case 0x22: printf("SHLD adr\n"); counter += 2; break;
            case 0x23: printf("INX  H\n"); break;
            case 0x24: printf("INR  H\n"); break;
            case 0x25: printf("DCR  H\n"); break;
            case 0x26: printf("MVI  H 0x%02x\n", tmp[1]); counter += 1; break;
            case 0x27: printf("DAA\n"); break;
            case 0x28: _unimpl(*tmp); return instructions;
            case 0x29: printf("DAD  H\n"); break;
            case 0x2a: printf("LHLD adr\n"); counter += 2; break;
            case 0x2b: printf("DCX  H\n"); break;
            case 0x2c: printf("INR  L\n"); break;
            case 0x2d: _unimpl(*tmp); return instructions;
            case 0x2e: printf("MVI  L 0x%02x\n", tmp[1]); counter += 1; break;
            case 0x2f: printf("CMA\n"); break;
            case 0x30: printf("SIM\n"); break;
            case 0x31: printf("LXI  SP 0x%02x,0x%02x\n", tmp[2], tmp[1]); counter += 2; break;
            case 0x32: printf("STA  adr\n"); counter += 2; break;
            case 0x33: _unimpl(*tmp); return instructions;
            case 0x34: printf("INR  M\n"); break;
            case 0x35: printf("DCR  M\n"); break;
            case 0x36: printf("MVI  M 0x%02x\n", tmp[1]); counter += 1; break;
            case 0x37: printf("STC\n"); break;
            case 0x38: _unimpl(*tmp); return instructions;
            case 0x39: _unimpl(*tmp); return instructions;
            case 0x3a: printf("LDA  adr\n"); counter += 2; break;
            case 0x3b: _unimpl(*tmp); return instructions;
            case 0x3c: printf("INR  A\n"); break;
            case 0x3d: printf("DCR  A\n"); break;
            case 0x3e: printf("MVI  A 0x%02x\n", tmp[1]); counter += 1; break;
            case 0x3f: _unimpl(*tmp); return instructions;
            case 0x40: _unimpl(*tmp); return instructions;
            case 0x41: printf("MOV  B C\n"); break;
            case 0x42: _unimpl(*tmp); return instructions;
            case 0x43: _unimpl(*tmp); return instructions;
            case 0x44: _unimpl(*tmp); return instructions;
            case 0x45: _unimpl(*tmp); return instructions;
            case 0x46: printf("MOV  B M\n"); break;
            case 0x47: printf("MOV  B A\n"); break;
            case 0x48: printf("MOV  C B\n"); break;
            case 0x49: _unimpl(*tmp); return instructions;
            case 0x4a: _unimpl(*tmp); return instructions;
            case 0x4b: _unimpl(*tmp); return instructions;
            case 0x4c: _unimpl(*tmp); return instructions;
            case 0x4d: _unimpl(*tmp); return instructions;
            case 0x4e: printf("MOV  C M\n"); break;
            case 0x4f: printf("MOV  C A\n"); break;
            case 0x50: _unimpl(*tmp); return instructions;
            case 0x51: _unimpl(*tmp); return instructions;
            case 0x52: _unimpl(*tmp); return instructions;
            case 0x53: _unimpl(*tmp); return instructions;
            case 0x54: _unimpl(*tmp); return instructions;
            case 0x55: _unimpl(*tmp); return instructions;
            case 0x56: printf("MOV  D M\n"); break;
            case 0x57: printf("MOV  D A\n"); break;
            case 0x58: _unimpl(*tmp); return instructions;
            case 0x59: _unimpl(*tmp); return instructions;
            case 0x5a: _unimpl(*tmp); return instructions;
            case 0x5b: _unimpl(*tmp); return instructions;
            case 0x5c: _unimpl(*tmp); return instructions;
            case 0x5d: _unimpl(*tmp); return instructions;
            case 0x5e: printf("MOV  E M\n"); break;
            case 0x5f: printf("MOV  E A\n"); break;
            case 0x60: _unimpl(*tmp); return instructions;
            case 0x61: printf("MOV  H C\n"); break;
            case 0x62: _unimpl(*tmp); return instructions;
            case 0x63: _unimpl(*tmp); return instructions;
            case 0x64: _unimpl(*tmp); return instructions;
            case 0x65: printf("MOV  H L\n"); break;
            case 0x66: printf("MOV  H M\n"); break;
            case 0x67: printf("MOV  H A\n"); break;
            case 0x68: printf("MOV  L B\n"); break;
            case 0x69: printf("MOV  L C\n"); break;
            case 0x6a: _unimpl(*tmp); return instructions;
            case 0x6b: _unimpl(*tmp); return instructions;
            case 0x6c: _unimpl(*tmp); return instructions;
            case 0x6d: _unimpl(*tmp); return instructions;
            case 0x6e: _unimpl(*tmp); return instructions;
            case 0x6f: printf("MOV  L A\n"); break;
            case 0x70: printf("MOV  M B\n"); break;
            case 0x71: printf("MOV  M C\n"); break;
            case 0x72: printf("MOV  M D\n"); break;
            case 0x73: printf("MOV  M E\n"); break;
            case 0x74: printf("MOV  M H\n"); break;
            case 0x75: printf("MOV  M L\n"); break;
            case 0x76: printf("HLT\n"); break;
            case 0x77: printf("MOV  M A\n"); break;
            case 0x78: printf("MOV  A B\n"); break;
            case 0x79: printf("MOV  A C\n"); break;
            case 0x7a: printf("MOV  A D\n"); break;
            case 0x7b: printf("MOV  A E\n"); break;
            case 0x7c: printf("MOV  A H\n"); break;
            case 0x7d: printf("MOV  A L\n"); break;
            case 0x7e: printf("MOV  A M\n"); break;
            case 0x7f: printf("MOV  A A\n"); break;
            case 0x80: printf("ADD  B\n"); break;
            case 0x81: printf("ADD  C\n"); break;
            case 0x82: printf("ADD  D\n"); break;
            case 0x83: printf("ADD  E\n"); break;
            case 0x84: printf("ADD  H\n"); break;
            case 0x85: printf("ADD  L\n"); break;
            case 0x86: printf("ADD  M\n"); break;
            case 0x87: _unimpl(*tmp); return instructions;
            case 0x88: _unimpl(*tmp); return instructions;
            case 0x89: _unimpl(*tmp); return instructions;
            case 0x8a: printf("ADC  D\n"); break;
            case 0x8b: _unimpl(*tmp); return instructions;
            case 0x8c: _unimpl(*tmp); return instructions;
            case 0x8d: _unimpl(*tmp); return instructions;
            case 0x8e: _unimpl(*tmp); return instructions;
            case 0x8f: printf("ADC  A\n"); break;
            case 0x90: _unimpl(*tmp); return instructions;
            case 0x91: _unimpl(*tmp); return instructions;
            case 0x92: _unimpl(*tmp); return instructions;
            case 0x93: _unimpl(*tmp); return instructions;
            case 0x94: _unimpl(*tmp); return instructions;
            case 0x95: _unimpl(*tmp); return instructions;
            case 0x96: _unimpl(*tmp); return instructions;
            case 0x97: _unimpl(*tmp); return instructions;
            case 0x98: printf("SBB  B\n"); break;
            case 0x99: _unimpl(*tmp); return instructions;
            case 0x9a: _unimpl(*tmp); return instructions;
            case 0x9b: _unimpl(*tmp); return instructions;
            case 0x9c: _unimpl(*tmp); return instructions;
            case 0x9d: _unimpl(*tmp); return instructions;
            case 0x9e: _unimpl(*tmp); return instructions;
            case 0x9f: _unimpl(*tmp); return instructions;
            case 0xa0: printf("ANA  B\n"); break;
            case 0xa1: _unimpl(*tmp); return instructions;
            case 0xa2: _unimpl(*tmp); return instructions;
            case 0xa3: _unimpl(*tmp); return instructions;
            case 0xa4: _unimpl(*tmp); return instructions;
            case 0xa5: _unimpl(*tmp); return instructions;
            case 0xa6: printf("ANA  M\n"); break;
            case 0xa7: printf("ANA  A\n"); break;
            case 0xa8: _unimpl(*tmp); return instructions;
            case 0xa9: _unimpl(*tmp); return instructions;
            case 0xaa: _unimpl(*tmp); return instructions;
            case 0xab: _unimpl(*tmp); return instructions;
            case 0xac: _unimpl(*tmp); return instructions;
            case 0xad: _unimpl(*tmp); return instructions;
            case 0xae: _unimpl(*tmp); return instructions;
            case 0xaf: printf("XRA  A\n"); break;
            case 0xb0: printf("ORA  B\n"); break;
            case 0xb1: _unimpl(*tmp); return instructions;
            case 0xb2: _unimpl(*tmp); return instructions;
            case 0xb3: _unimpl(*tmp); return instructions;
            case 0xb4: printf("ORA  H\n"); break;
            case 0xb5: _unimpl(*tmp); return instructions;
            case 0xb6: printf("ORA  M\n"); break;
            case 0xb7: _unimpl(*tmp); return instructions;
            case 0xb8: printf("CMP  B\n"); break;
            case 0xb9: _unimpl(*tmp); return instructions;
            case 0xba: _unimpl(*tmp); return instructions;
            case 0xbb: _unimpl(*tmp); return instructions;
            case 0xbc: printf("CMP  H\n"); break;
            case 0xbd: _unimpl(*tmp); return instructions;
            case 0xbe: printf("CMP  M\n"); break;
            case 0xbf: _unimpl(*tmp); return instructions;
            case 0xc0: printf("RNZ\n"); break;
            case 0xc1: printf("POP  B\n"); break;
            case 0xc2: printf("JNZ  adr\n"); counter += 2; break;
            case 0xc3: printf("JMP  0x%02x%02x\n", tmp[2], tmp[1]); counter += 2; break;
            case 0xc4: printf("CNZ  adr\n"); counter += 2; break;
            case 0xc5: printf("PUSH B\n"); break;
            case 0xc6: printf("ADI  0x%02x\n", tmp[1]); counter += 1; break;
            case 0xc7: _unimpl(*tmp); return instructions;
            case 0xc8: printf("RZ\n"); break;
            case 0xc9: printf("RET\n"); break;
            case 0xca: printf("JZ   adr\n"); counter += 2; break;
            case 0xcb: _unimpl(*tmp); return instructions;
            case 0xcc: printf("CZ   adr\n"); counter += 2; break;
            case 0xcd: printf("CALL adr\n"); counter += 2; break;
            case 0xce: _unimpl(*tmp); return instructions;
            case 0xcf: _unimpl(*tmp); return instructions;
            case 0xd0: printf("RNC\n"); break;
            case 0xd1: printf("POP  D\n"); break;
            case 0xd2: printf("JNC  adr\n"); break;
            case 0xd3: printf("OUT  0x%02x\n", tmp[1]); counter += 1; break;
            case 0xd4: printf("CNC  adr\n"); counter += 2; break;
            case 0xd5: printf("PUSH D\n"); break;
            case 0xd6: printf("SUI  0x%02x\n", tmp[1]); counter += 1; break;
            case 0xd7: _unimpl(*tmp); return instructions;
            case 0xd8: printf("RC\n"); break;
            case 0xd9: _unimpl(*tmp); return instructions;
            case 0xda: printf("JC   adr\n"); counter += 2; break;
            case 0xdb: printf("IN   0x%02x\n", tmp[1]); counter += 1; break;
            case 0xdc: _unimpl(*tmp); return instructions;
            case 0xdd: _unimpl(*tmp); return instructions;
            case 0xde: printf("SBI  0x%02x\n", tmp[1]); counter += 1; break;
            case 0xdf: _unimpl(*tmp); return instructions;
            case 0xe0: _unimpl(*tmp); return instructions;
            case 0xe1: printf("POP  H\n"); break;
            case 0xe2: _unimpl(*tmp); return instructions;
            case 0xe3: printf("XTHL\n"); break;
            case 0xe4: _unimpl(*tmp); return instructions;
            case 0xe5: printf("PUSH H\n"); break;
            case 0xe6: printf("ANI  0x%02x\n", tmp[1]); counter += 1; break;
            case 0xe7: _unimpl(*tmp); return instructions;
            case 0xe8: _unimpl(*tmp); return instructions;
            case 0xe9: printf("PCHL\n"); break;
            case 0xea: _unimpl(*tmp); return instructions;
            case 0xeb: printf("XCHX\n"); break;
            case 0xec: _unimpl(*tmp); return instructions;
            case 0xed: _unimpl(*tmp); return instructions;
            case 0xee: _unimpl(*tmp); return instructions;
            case 0xef: _unimpl(*tmp); return instructions;
            case 0xf0: _unimpl(*tmp); return instructions;
            case 0xf1: printf("POP  PSW\n"); break;
            case 0xf2: _unimpl(*tmp); return instructions;
            case 0xf3: _unimpl(*tmp); return instructions;
            case 0xf4: _unimpl(*tmp); return instructions;
            case 0xf5: printf("PUSH PSW\n"); break;
            case 0xf6: printf("ORI  0x%02x\n", tmp[1]); counter += 1; break;
            case 0xf7: _unimpl(*tmp); return instructions;
            case 0xf8: _unimpl(*tmp); return instructions;
            case 0xf9: printf("SPHL\n"); break;
            case 0xfa: printf("JM   adr\n"); counter += 2; break;
            case 0xfb: printf("EI\n"); break;
            case 0xfc: _unimpl(*tmp); return instructions;
            case 0xfd: _unimpl(*tmp); return instructions;
            case 0xfe: printf("CPI  0x%02x\n", tmp[1]); counter += 1; break;
            case 0xff: printf("RST  7"); break;
            default: _unimpl(*tmp); return instructions;
        }
        instructions += 1;
        counter += 1;
    }
    return instructions;
}
